[Added] Chinese
axios/axios-docs pull request #21
Opened 2021-04-07 18:24 UTC by heng1025

add Chinese translation

2021-04-08 07:40 UTC, codemaster138 approved these changes
I don't know Chinese, so I can't guarantee this translation is correct, but I can say this is a very solid PR!

/cc @jasonsaayman

2021-04-08 08:01 UTC, jasonsaayman commented
@codemaster138 I am waiting for @chinesedfan to see if he can review since he is a native Chinese speaker, let's give him a couple day's else I will merge.

2021-04-09 18:51 UTC, codemaster138 commented
@jasonsaayman Has @chinesedfan taken a look at this yet?

2021-04-10 01:00 UTC, chinesedfan commented
Looking. Will give feedbacks this weekend.

2021-04-10 03:17 UTC, chinesedfan requested changes
Added some comments. By the way, shall we maintain those /public html files in git? Looks like auto-generated.

2021-04-10 03:17 UTC, chinesedfan commented on posts/zh/urlencoded.md
> +> 请注意，所有的浏览器(参见 [caniuse.com](http://www.caniuse.com/#feat=urlsearchparams))都不支持 `URLSearchParams` ，但是可以使用[polyfill](https://github.com/WebReflection/url-search-params) (确保 polyfill 全局环境)
```suggestion
> 请注意，不是所有的浏览器(参见 [caniuse.com](http://www.caniuse.com/#feat=urlsearchparams))都支持 `URLSearchParams` ，但是可以使用[polyfill](https://github.com/WebReflection/url-search-params) (确保 polyfill 全局环境)
```

2021-04-10 03:17 UTC, chinesedfan commented on posts/zh/handling_errors.md
> +使用 `toJSON` 可以获取更多关于HTTP的错误信息。
```suggestion
使用 `toJSON` 可以获取更多关于HTTP错误的信息。
```

2021-04-10 03:17 UTC, chinesedfan commented on posts/zh/api_intro.md
> +为了方便起，已经为所有支持的请求方法提供了别名。
```suggestion
为了方便起见，已经为所有支持的请求方法提供了别名。
```

2021-04-10 07:06 UTC, codemaster138 commented
> By the way, shall we maintain those /public html files in git? Looks like auto-generated.

@chinesedfan No, those public files don't need to be in git. The only reason I didn't add them to the .gitignore is that I thought we'd be hosting with GitHub pages, but since we're not, you can delete them.

2021-04-11 04:39 UTC, heng1025 commented
> > By the way, shall we maintain those /public html files in git? Looks like auto-generated.
> 
> @chinesedfan No, those public files don't need to be in git. The only reason I didn't add them to the .gitignore is that I thought we'd be hosting with GitHub pages, but since we're not, you can delete them.

Github Action also can achieve same goal, even if there were not /public html files.

2021-04-11 05:34 UTC, chinesedfan approved these changes

2021-04-11 10:12 UTC, codemaster138 commented
> > > By the way, shall we maintain those /public html files in git? Looks like auto-generated.
> > 
> > 
> > @chinesedfan No, those public files don't need to be in git. The only reason I didn't add them to the .gitignore is that I thought we'd be hosting with GitHub pages, but since we're not, you can delete them.
> 
> Github Action also can achieve the same goal, even if there were not /public html files.

Yeah, I know, I guess I just wasn't thinking very hard 😅

2021-04-12 05:57 UTC, jasonsaayman commented
@codemaster138 please open a new pull request that will handle the public HTML files, for now, I will merge this.

2021-04-12 05:57 UTC, merged